### ISSUE TITLE
Should Caster define default phrases which plugins can refer to?

### ISSUE THREAD

**Issue by Timoses** [Timoses/Caster#10]
Caster could define default phrases for example:
* confirming an action: "okay"
* rejecting an action: "reject"
* moving directions: "up", "down", "left", "right"
...

What could a good nomenclature before these kind of phrases?

These phrases could be overridden by users which would then also impact any plugins which are using these phrase references.

Could this functionality be provided by a plugin?

**Comment by LexiconCode** [comment]
This goes back how do we customize plug-ins without changing its code so that the users preferences are the source of truth even when the plug-ins update. This is even more important than allowing users to find their own context independently of the plug-in. Such a system needs to be independent of the target spec is trying to replace. Which is the current weakness of simplified transformers.

Regarding design philosophy of grammars I will be moving forward with https://github.com/dictation-toolbox/Caster/issues/625 designing grammars with Kim based on her philosophy for all caster rules/plug-ins.

This will include documentation users design their own grammars based on that philosophy as well.

**Comment by LexiconCode** [comment]
A bit of terminology:
- Specs are the sords of people say that trigger an action
- Actions perform some sort of interaction with the OS or program
- Commands reference are made up of a spec and an action

I believe plug-ins/grammars should have placeholders which can have defined default specs. If these placeholders evaluate to `none` the defaults are used.  A spec API could be used for this purpose.

User starts Caster the 1st time with X number of plug-ins that use the API. In the user profile list is generated of the default specs along with the API references. By changing those default specs in the user directory under each API reference it updates to reflect the user's spec preference.

What could such an API look like from a dev plug-in/grammar perspective? 
**Pseudocode**
- "zoom out [\<n>]":  Key("c-minus/20"), api=core.ZOOM_OUT_N_TIMES" `is the default as its initially defined.`
- "zoom in [\<n>]":  Key("c-minus/20"), api=core.ZOOM_IN_N_TIMES"

User perspective something like a text file in the user directory.
- core.ZOOM_OUT_N_TIMES = zoomer out [\<n>] `<- user customization`
- core.ZOOM_IN_N_TIMES `<- present but unused API reference which evaluates to none by default leaving the spec `zoom in [\<n>]` as default.

There a lot of other things to consider such a paradigm but the above is just to get the ball rolling.
- Validation of extras [\<n>] as they are needed for actions
- how long will these API references be handled in choice or other objects
- plug-in spec translations before user edits
- Targeting specs directly as not all plug-ins will use the API (fragile as mentioned with transformers)
- global changes versus plug-in/grammar specific changes
- and more

**Comment by Timoses** [comment]
I think again that this is something that can be accomplished via plugins.

E.g.:
* User specifies a pip package in the configuration which offers the ability to configure "variables". 
* These variables could be for example `dictation.alphabet.a`. 
* Any other plugin can reference these variables.
  * In effect: The plugin which uses these "variable packages" should declare a dependency on these, so they are always installed.

Plugins are powerful in this way. I wouldn't want to try to force "one way" on how to approach it, but rather offer the ability to try stuff out via plugins and see from there which requirements will come towards Caster Core.


===> This again means that users which implement plugins, grammars and the like have the power to experiment which opens up a landscape which can be discovered -> Perhaps on that path a best approach can be found.

**Comment by LexiconCode** [comment]
I get where you're coming from you want to be able to give developers the most freedom to develop the best product. That should be a goal but it does need to be balanced as it always adds complexity.

> Plugins are powerful in this way. I wouldn't want to try to force "one way" on how to approach it, but rather offer the ability to try stuff out via plugins and see from there which requirements will come towards Caster Core.
> 
> ===> This again means that users which implement plugins, grammars and the like have the power to experiment which opens up a landscape which can be discovered -> Perhaps on that path a best approach can be found.

You're looking at this purely from a developer perspective and not a user experience. Remember were most people come into this project most of them can barely interact with the computer with varying levels of developer experience they are not going to want to experiment at least 1st starting out. Even even that is too much as we should assume people without any developer experience come into the project. That means they need a complete system that works out of the box. Can we have the best of both worlds? Possibly

Going along with your idea. It means we need a standard set of well-designed plug-ins with the that implement features such as ones referenced in this issue that provide the community with the tools.

**Comment by LexiconCode** [comment]
Perhaps in a new issue it would be helpful to break down the current Caster 2 feature set into plug-ins. Outlining this now helps us determine which plug-ins to implement 1st as it may change how subsequent plug-ins interact as they require features.

For example caster 2 feature could be `transformers` which would need to be re-implemented into a plug-in.

**Comment by Timoses** [comment]
I agree. Plugins offer the freedom, and offering specially tailored and thought-through plugins to the community including documentation a potential for easy usability.

I'd be in favor for creating a new issue where
* a plugin structure is developed to represent current Caster2 functionality
* from that strategies on how to best implement it
    * e.g. is there a common ground for all plugins? 
    * What components are shared between plugins?
    * Find the features that Caster Core must offer to support this plugin infrastructure (or required features).

Regarding transformers: I never used them but feel like they offer a too complex and broad interface. I mentioned this a couple of times: A plugin should be goal-oriented in fulfilling a specific purpose. Configurable options (e.g. what words should be used for an action of the plugin or e.g. what Keepass Database to use, should be accessed through a configuration interface offered by Caster; so every plugin can be configured as required).


I'm in favor of closing this issue and creating a new one; something along the way "Rethink Caster into plugins".

**Comment by LexiconCode** [comment]
> I'd be in favor for creating a new issue where
> 
>     * a plugin structure is developed to represent current Caster2 functionality
> 
>     * from that strategies on how to best implement it
>       
>       * e.g. is there a common ground for all plugins?
>       * What components are shared between plugins?
>       * Find the features that Caster Core must offer to support this plugin infrastructure (or required features).
> 

I think this would be a really good process to go through as a high level overview of features and answering some of those questions. Once we boil that down perhaps implementation should be broken up into issues per feature? from there we can then create projects breaking down the steps that we need for implementation.

Perhaps we should split into a number of repositories as soon as possible?
- Core implementation (Caster Core)
- Caster plug-ins (represents the core features of Caster) this repository which will become upstream?
- GUI front end?

That also help delineate the design paradigm close to what we will see in the final product. 

> Regarding transformers: I never used them but feel like they offer a too complex and broad interface. I mentioned this a couple of times: A plugin should be goal-oriented in fulfilling a specific purpose. Configurable options (e.g. what words should be used for an action of the plugin or e.g. what Keepass Database to use, should be accessed through a configuration interface offered by Caster; so every plugin can be configured as required).
> 

The goal of transformers or any other implementation is to allow user edits to be the single source of truth that survive updates without having to edit code. This is a heavily used feature of caster currently. I really do think this is a core issue that does need to be addressed somewhere in the project.  We both agree that there needs to be this functionality?  Once we've mapped out the plug-in structure I think we both will have a better idea how to address this topic in terms of scope and implementation.

**Comment by Timoses** [comment]
> Perhaps we should split into a number of repositories as soon as possible? The upstream repository can act as a hub between the following repositories:
    Core implementation (Caster Core)
    Caster plug-ins(represents the features of Caster).
    GUI front end?
    
I was about to suggest something similar. It would probably be a good idea to create a `caster-plugins` repository or similar which focuses on implementing the known Caster functionality. Structuring that repository will be an organizational task. 

A GUI frontend should probably also go into a separate repository. Where it interfaces to I'm not sure.. Perhaps Caster-Core serves a web-based browser GUI. Or a GUI client attaches to Caster-Core as a server... Perhaps this belongs in another issue.



> The goal of transformers or any other implementation is to allow user edits to be the single source of truth that survive updates without having to edit code. This is a heavily used feature of caster currently. I really do think this is a core issue that does need to be addressed somewhere in the project. We both agree that there needs to be this functionality? Once we've mapped out the plug-in structure I think we both will have a better idea how to address this topic in terms of scope and implementation.

What I read from that is that Caster-Core should provide stable APIs which plugins use and should perhaps be able to specify which version of caster is supported (https://github.com/Timoses/Caster/issues/9). The lifecycle of a plugin should be managed by plugin maintainers and not by the user (the user merely configures the plugin).


I'd also think that using the current `Caster` repository as a "hub" is a good idea. It can reference the other repositories and remain the focal point for design discussions etc.

What do you think about the repository names:
* `caster-core`
* `caster-plugins`
?

**Comment by LexiconCode** [comment]
> A GUI frontend should probably also go into a separate repository. Where it interfaces to I'm not sure.. Perhaps Caster-Core serves a web-based browser GUI. Or a GUI client attaches to Caster-Core as a server... Perhaps this belongs in another issue.

I agree new issue should be made to discuss what the GUI is meant to display and how it connects to the backed implementation.

> What I read from that is that Caster-Core should provide stable APIs which plugins use and should perhaps be able to specify which version of caster is supported (#9). The lifecycle of a plugin should be managed by plugin maintainers and not by the user (the user merely configures the plugin).

What I meant by core issue not necessarily where it's implemented e.g. castor core. This issue of customization is going to be crucial for the success of the community. Leaving it up to the plug-in developer and to come up with their own implementation is problematic. Like I said let's get everything organized 1st in some of these other things before we pursue thinking about that in-depth whether core or plug-in.

> I'd also think that using the current `Caster` repository as a "hub" is a good idea. It can reference the other repositories and remain the focal point for design discussions etc.
> 
> What do you think about the repository names:
> 
>     * `caster-core`
> 
>     * `caster-plugins`
>       ?

I'm good with those repository names. The current `Caster` repository as a "hub" but also could be used for the GUI. The GUI could be downloaded by the end user and that is the entry point for them into the project. When the GUI 1st runs the user could be guided through the necessary or automated set up for Python, plug-ins, and so on.

**Comment by Timoses** [comment]
Sounds great : ). Are you able to create the repos `caster-core` and `caster-plugins`? I could split up my current caster3 branch and create pull requests in caster-core and caster-plugins (I'd move the dictation and bringme there already).

**Comment by LexiconCode** [comment]
https://github.com/CasterVoice?type=source

**Comment by Timoses** [comment]
Great. Closing this issue.

Default phrases may be implemented elsewhere (e.g. in https://github.com/CasterVoice/caster-plugins ); not in Caster Core.
