### ISSUE TITLE
Transition from travis to github actions

### ISSUE THREAD

**Issue by LexiconCode** [Timoses/Caster#18]
I could make a PR, I have laid out the reasons in https://github.com/dictation-toolbox/Caster/pull/867

It should be pretty trivial to adopt a simplified version of `.github/workflows/pythonpackage.yml` from upstream.

**Comment by Timoses** [comment]
Ah great. Did not see this issue until now.

I've transferred the current tests to GitHub Actions already here: https://github.com/CasterVoice/caster-core/pull/1/commits/c7abcd2944aed065e61330f3ceea2c5bbd9947ba
